# Generated by Django 5.0.7 on 2024-07-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='weather_now',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
